### PR TITLE
added unit tests for `exceptions.go`

### LINKED ISSUE #45: add unit tests for exceptions.go
I would like to add unit tests for `cmd/exceptions.go`

### PR DESCRIPTION
**Pull request by khareyash05**
Fixes #45

### CODE REVIEW

**Comment by khareyash05** [comment]
@dangoor Kindly review!

**Comment by dangoor** [comment]
@khareyash05 Thanks for sending us this PR! We should be able to review it early next week.

**Comment by elrayle** [comment]
@khareyash05 I've been out sick for the last few weeks which delayed the review.  Thanks for submitting and for your patience.

A general observation, the test is testing how the function achieves its result by testing reading/writing files and marshaling/unmarshaling json.  Typically a unit test is used, treating the function as a black box where input is passed to a function and the test checks that the function returns the expected output. 

Unfortunately, the function isn't currently structured that way.  In it's current form, the input and output files are hardcoded in the function meaning that running the test would replace the output files which hold data used by the spdxexp package.

There needs to be refactoring of the function to receive the input file and return the output files to facilitate the testing process.

**Comment by khareyash05** [comment]
> @khareyash05 I've been out sick for the last few weeks which delayed the review. Thanks for submitting and for your patience.
> 
> A general observation, the test is testing how the function achieves its result by testing reading/writing files and marshaling/unmarshaling json. Typically a unit test is used, treating the function as a black box where input is passed to a function and the test checks that the function returns the expected output.
> 
> Unfortunately, the function isn't currently structured that way. In it's current form, the input and output files are hardcoded in the function meaning that running the test would replace the output files which hold data used by the spdxexp package.
> 
> There needs to be refactoring of the function to receive the input file and return the output files to facilitate the testing process.

Kindly correct me if I am wrong - You are  suggesting me that the `extractExceptionLicenseIDs()` function in `exceptions.go` needs to be refactored in order to test my code for all cases right? and that the function needs input and output files as params?

**Comment by elrayle** [comment]
@khareyash05 This has taken way too long for me to respond.  My apologies for that and I appreciate your patience and desire to contribute.  

Recommended Refactor:
* create a separate function `func jsonForExceptionLicenseIDs(exceptionFileName string) error` that holds all the current code from function `extractExceptionLicenseIDs` except the final write to a file
* update `exceptions.go` function `extractExceptionLicenseIDs` to call `jsonForExceptionLicenseIDs("exceptions.json")` and then do the write to `exception_ids.json`
* create test file (e.g. `cmd/fixtures/exceptions.json`) with a few exceptions license IDs
* in the test, call `jsonForExceptionLicenseIDs("fixtures/exceptions.json")` and test that the generated json is as expected

**Pull request closed without merging**
